version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pkmn_tracker_db
    environment:
      POSTGRES_DB: pkmn_tracker_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d pkmn_tracker_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 